{% set version = "0.3.2" %}
{% set sha256 = "c20239fe3dcf6bd2ac957395b712f52e630c83a38d5347e7a3e6dce718ad4fe1" %}

package:
  name: mtspec
  version: {{ version }}


source:
  fn: mtspec-{{ version }}.zip
  url: https://pypi.io/packages/source/m/mtspec/mtspec-{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    - win_compile.patch  # [win]

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt
  script:
    - python setup.py build --compiler=mingw32  # [win32]
    - python setup.py build --compiler=mingw64  # [win64]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - gcc  # [not win]
    - m2w64-toolchain  # [win]
    - numpy
  run:
    - python
    - libgfortran  # [not win]
    - m2w64-gcc-libgfortran  # [win]
    - numpy

test:
  imports:
    - mtspec
  commands:
    - python -m mtspec.tests

about:
  home: http://github.com/krischer/mtspec
  license: GPL-3.0
  summary: 'Python library for multitaper spectral estimations'
  description: |
    mtspec is a Python (ctypes) wrapper for the Multitaper Spectrum Estimation
    Library mwlib.a by German A. Prieto.
    It enables you to calculate Slepian windows, perform multitaper spectral
    estimations with various options, calculate Wigner-Ville time-frequency
    distributions, and construct coherence spectra with multitapers.
  doc_url: http://krischer.github.io/mtspec/
  dev_url: https://github.com/krischer/mtspec

extra:
  recipe-maintainers:
    - krischer
    - ocefpaf
