travis:
  secure:
    BINSTAR_TOKEN: AB/E/i5qQCcYYU3jE3XwtTWZ29PYj5B4r9YuXifghvZk2kyWB8bolnElmLh/jlS5d9COOYuXgkoWE24xGxOFdzPWQ8T9JiEK7QDk0++XKBUF9aitFKXL+Hgt4WtVeE4JotGshmXxslrEOUK57w5GJ+usAbUkdtxP2n63xZbc346C1je/ntoiIvcG2ExvUGjx9+9mhJGlED+wiJLdYfL8k/TMW+smTJYGwxODhi9J8UCiG8YJfAxZOP7iKwhZM1TIITJzfO4begreqDsUBXcAvTE7nVB6+cTzBt0xYn60979JMhNrlZlWzYi6eRX4zg8dFAjthBw5ir6BvV0vJwS/A40gT3fcEBIEaIcyYcZlB3Gczh4GX2fKo318hNjjNVGHuofZ5a+HWSLGOZ7Hvccw7jTJJxWbp5tSzQzwu8R7RoOvaKEiPdP/tOimQv2sDVVtNADzEh1be2tcMeK8YCLnnybCpi0a1zdjFbVkjcCbjQniYCcaUFOmaVbipsYgKxTXrj1XOr2inBIWOG44u9M5avWnxmRGYqXue1szXYIBFRo8Id3Y5HVOMFebK2xj1A0wggC+VDYt2Gsbbn9T4uxmwM2hxXqLitkzV9cRNJNnhJWn8H6jNBT+4KgyaED1/cfYgKAedNYZ5wKCgOpp1E//nBqCbEhNy0CoazjooohTh/I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
